Readium.Models.PackageDocumentBase=Backbone.Model.extend({initialize:function(a,b){if(b&&b.file_path){this.file_path=b.file_path;var c=this;b.root_url?c.uri_obj=new URI(b.root_url):Readium.FileSystemApi(function(a){a.getFsUri(c.file_path,function(a){c.uri_obj=new URI(a)})})}},jath_template:{metadata:{id:"//def:metadata/dc:identifier",epub_version:"//def:package/@version",title:"//def:metadata/dc:title",author:"//def:metadata/dc:creator",publisher:"//def:metadata/dc:publisher",description:"//def:metadata/dc:description",
rights:"//def:metadata/dc:rights",language:"//def:metadata/dc:language",pubdate:"//def:metadata/dc:date",modified_date:"//def:metadata/def:meta[@property='dcterms:modified']",layout:"//def:metadata/def:meta[@property='rendition:layout']",spread:"//def:metadata/def:meta[@property='rendition:spread']",orientation:"//def:metadata/def:meta[@property='rendition:orientation']",ncx:"//def:spine/@toc",page_prog_dir:"//def:spine/@page-progression-direction"},manifest:["//def:item",{id:"@id",href:"@href",media_type:"@media-type",
properties:"@properties",media_overlay:"@media-overlay"}],spine:["//def:itemref",{idref:"@idref",properties:"@properties"}],bindings:["//def:bindings/def:mediaType",{handler:"@handler",media_type:"@media-type"}]},getCoverHref:function(a){var b,c;b=a.getElementsByTagName("manifest")[0];c=$('item[properties~="cover-image"]',b);if(c.length===1&&c.attr("href"))return c.attr("href");a=$('meta[name="cover"]',a);c=a.attr("content");if(a.length===1&&c&&(c=$('item[id="'+c+'"]',b),c.length===1&&c.attr("href")))return c.attr("href");
c=$("#cover",b);return c.length===1&&c.attr("href")?c.attr("href"):null},parseSpineProperties:function(a){for(var b=function(a){for(var b={},a=a.split(" "),c=0;c<a.length;c++){if(a[c]==="rendition:page-spread-center")b.page_spread="center";if(a[c]==="page-spread-left")b.page_spread="left";if(a[c]==="page-spread-right")b.page_spread="right";if(a[c]==="page-spread-right")b.page_spread="right";if(a[c]==="rendition:layout-reflowable")b.fixed_flow=!1;if(a[c]==="rendition:layout-pre-paginated")b.fixed_flow=
!0}return b},c=0;c<a.length;c++){var e=b(a[c].properties);_.extend(a[c],e)}return a},resolveMediaOverlays:function(a){var b=this,c={};a.forEach(function(a){if(a.get("media_type")==="application/smil+xml"){var d=b.resolveUri(a.get("href")),d=new Readium.Models.MediaOverlay({smil_url:d});d.fetch();c[a.id]=d}});return c},paginateBackwards:function(a){return $("spine",a).attr("page-progression-direction")==="ltr"},parse:function(a){var b;typeof a==="string"&&(a=(new window.DOMParser).parseFromString(a,
"text/xml"));Jath.resolver=function(a){return{def:"http://www.idpf.org/2007/opf",dc:"http://purl.org/dc/elements/1.1/"}[a]};b=Jath.parse(this.jath_template,a);b.paginate_backwards=this.paginateBackwards(a);if(a=this.getCoverHref(a))b.metadata.cover_href=this.resolveUri(a);if(b.metadata.layout==="pre-paginated")b.metadata.fixed_layout=!0;b.manifest=new Readium.Collections.ManifestItems(b.manifest,{packageDocument:this});b.mo_map=this.resolveMediaOverlays(b.manifest);b.spine=this.parseSpineProperties(b.spine);
return b},crunchSpine:function(a,b){var c=this,e=-1,d=_.map(a,function(a){e+=1;var d=b.find(function(b){if(b.get("id")===a.idref)return b}),f=c.get("book");return _.extend({},a,d.attributes,{spine_index:e},{page_prog_dir:f.get("page_prog_dir")})});return new Readium.Collections.Spine(d,{packageDocument:this})},reset:function(a){this.set(this.parse(a))},resolveUri:function(a){uri=new URI(a);return uri.resolve(this.uri_obj).toString()},resolvePath:function(a){var b=this.file_path,a=a.indexOf("../")===
0?a.substr(3):a,c=b.lastIndexOf("/");return b.substr(0,c)+"/"+a}});
Readium.Models.ValidatedPackageMetaData=Readium.Models.PackageDocumentBase.extend({initialize:function(a,b){Readium.Models.PackageDocumentBase.prototype.initialize.call(this,a,b);this.set("package_doc_path",this.file_path)},validate:function(){},defaults:{fixed_layout:!1,apple_fixed:!1,open_to_spread:!1,cover_href:"/images/library/missing-cover-image.png",created_at:new Date,updated_at:new Date,paginate_backwards:!1},parseIbooksDisplayOptions:function(a){var b=(new window.DOMParser).parseFromString(a,
"text/xml"),a=b.getElementsByName("fixed-layout")[0],b=b.getElementsByName("open-to-spread")[0];this.set({fixed_layout:a&&a.textContent.toLowerCase().trim()==="true",open_to_spread:b&&b.textContent.toLowerCase().trim()==="true",apple_fixed:a&&a.textContent.toLowerCase().trim()==="true"})},parse:function(a){return Readium.Models.PackageDocumentBase.prototype.parse.call(this,a).metadata},save:function(a,b){var c=this;this.set("updated_at",new Date);Lawnchair(function(){this.save(c.toJSON(),b.success)})}});
Readium.Models.PackageDocument=Readium.Models.PackageDocumentBase.extend({initialize:function(a,b){Readium.Models.PackageDocumentBase.prototype.initialize.call(this,a,b);this.on("change:spine_position",this.onSpinePosChanged)},onSpinePosChanged:function(){this.get("spine_position")>=this.previous("spine_position")?this.trigger("increased:spine_position"):this.trigger("decreased:spine_position")},validate:function(a){if(!a.manifest&&!this.get("manifest"))return"ERROR: All ePUBs must have a manifest";
var b=a.spine||this.get("spine");if(!b)return"ERROR: All ePUBs must have a spine";if(a.spine_position<0||a.spine_position>=b.length)return"ERROR: invalid spine position"},sync:BBFileSystemSync,defaults:{spine_position:0},getManifestItemById:function(a){return this.get("manifest").find(function(b){if(b.get("id")===a)return b})},getSpineItem:function(a){return this.get("res_spine").at(a)},spineLength:function(){return this.get("res_spine").length},goToNextSection:function(){this.set({spine_position:this.get("spine_position")+
1})},goToPrevSection:function(){this.set({spine_position:this.get("spine_position")-1})},spineIndexFromHref:function(a){for(var b=this.get("res_spine"),a=this.resolveUri(a).replace(/#.*$/,""),c=0;c<b.length;c++){var e=b.at(c).get("href"),e=this.resolveUri(e).replace(/#.*$/,"");if(e===a)return c}return-1},goToHref:function(a){var b=this.get("spine"),c=this.get("manifest"),e=this,a=e.resolveUri(a).replace(/#.*$/,""),c=c.find(function(b){var c=e.resolveUri(b.get("href")).replace(/#.*$/,"");if(a==c)return b});
if(!c)return null;for(var c=c.get("id"),d=0;d<b.length;++d)if(b[d].idref===c){this.set({spine_position:d},{silent:!0});this._previousAttributes.spine_position=0;this.trigger("change:spine_position");break}},getTocItem:function(){var a=this.get("manifest"),b=this.get("metadata").ncx,c=a.find(function(a){return a.get("properties")==="nav"});return c?c:b&&b.length>0?a.find(function(a){return a.get("id")===b}):null},getMediaOverlayItem:function(a){var b=this.get("mo_map");return b&&b[a]},parse:function(a){a=
Readium.Models.PackageDocumentBase.prototype.parse.call(this,a);a.res_spine=this.crunchSpine(a.spine,a.manifest);return a}});
